// SPDX-License-Identifier: MIT
#pragma once

#include "CoreMinimal.h"
#include "UObject/Class.h"

/**
 * Strict resolution of a caller-supplied enum VALUE against the UEnum that will store it.
 *
 * WHY THIS FILE EXISTS (gap #46).
 * set_renderer_property resolved enum values like this:
 *
 *     int64 EV = E->GetValueByNameString(JV->AsString());
 *     if (EV == INDEX_NONE) EV = static_cast<int64>(JV->AsNumber());
 *
 * The second line is the defect. FJsonValue::AsNumber() on a non-numeric string answers 0, so
 * ANY unrecognised name was stored as enum entry 0 and the action still reported "Property set".
 * Measured 2026-08-17: Alignment="ZZZ_NotAnEnum" stored Alignment=Unaligned with no warning.
 *
 * It is worse than a silent no-op, because entry 0 is usually the CDO default and therefore
 * stops being delta-serialised. A garbage `shape` passed to configure_ribbon one call after
 * preset=tube left Shape reverted to Plane while TubeSubdivisions=8 SURVIVED — a half-applied
 * preset, a state no legitimate call could produce, so "just re-apply the preset" is not
 * reliable recovery. A refusal is.
 *
 * The precedent for refusing is already in the same handler: an unknown property NAME errors
 * with "Property 'X' not found". This is that rule extended from names to values, and it matches
 * what gap #27 / I-18 did for bool and int, and what MonolithMaterialActions::ParseEnum and
 * MonolithBlueprintInternal::ResolveEnumValueFromRaw already do in their namespaces.
 *
 * The DECISION — "is this token a legal value of this enum" — needs a UEnum and nothing else:
 * no asset, no emitter, no editor. So it lives here, pure and header-inline, and is unit-tested
 * against real engine enums in Private/Tests/MonolithNiagaraEnumValueTest.cpp.
 */
namespace MonolithNiagaraEnumValue
{
	/** UHT appends _MAX to most UENUMs; some hand-written ones append _NUM. Neither is a value a caller means. */
	inline bool IsSentinelEnumName(const FString& Name)
	{
		return Name.EndsWith(TEXT("_MAX")) || Name.EndsWith(TEXT("_NUM"));
	}

	/**
	 * The entries a caller may legitimately pass, comma-joined, for use in a refusal message.
	 * Sentinels and entries hidden from the editor are dropped: they are storable but are not
	 * answers to "what should I have said instead".
	 */
	inline FString DescribeValidValues(const UEnum* Enum)
	{
		if (!Enum)
		{
			return FString();
		}

		TArray<FString> Names;
		for (int32 Index = 0; Index < Enum->NumEnums(); ++Index)
		{
			const FString Name = Enum->GetNameStringByIndex(Index);
			if (Name.IsEmpty() || IsSentinelEnumName(Name))
			{
				continue;
			}
#if WITH_METADATA
			if (Enum->HasMetaData(TEXT("Hidden"), Index))
			{
				continue;
			}
#endif
			Names.AddUnique(Name);
		}
		return FString::Join(Names, TEXT(", "));
	}

	/** True when Enum is declared UENUM(meta=(Bitflags)) — its legal values are combinations, not declared entries. */
	inline bool IsBitflagsEnum(const UEnum* Enum)
	{
#if WITH_METADATA
		return Enum && Enum->HasMetaData(TEXT("Bitflags"));
#else
		return false;
#endif
	}

	/**
	 * Is InValue storable in Enum?
	 * For an ordinary enum the value must be one the enum declares. For a Bitflags enum any
	 * combination is legal by construction, so only the declared-entry test is skipped —
	 * this is the one place a number is taken on trust, and only because the type says so.
	 *
	 * KNOWN EDGE, stated rather than hidden: IsValidEnumValue accepts the autogenerated _MAX
	 * entry. Passing that number therefore succeeds even though DescribeValidValues will not
	 * offer it. Rejecting it would mean guessing at shape rather than asking the engine.
	 */
	inline bool IsStorableEnumValue(const UEnum* Enum, int64 InValue)
	{
		if (!Enum)
		{
			return false;
		}
		return IsBitflagsEnum(Enum) || Enum->IsValidEnumValue(InValue);
	}

	/**
	 * Resolve a STRING token to an enum value, or refuse.
	 *
	 * Accepted spellings, in order:
	 *   1. the short, prefixed or fully-qualified entry name (UEnum::GetValueByNameString handles all three);
	 *   2. a short name against the enum's own underscore prefix ("Opaque" -> "BLEND_Opaque");
	 *   3. a bare integer, but ONLY when the enum declares that value — so a stray number never
	 *      invents an entry, which is the half of the old behaviour that did the damage.
	 *
	 * KNOWN EDGE: an enum that legitimately declares -1 is indistinguishable from "not found"
	 * here, because GetValueByNameString reports failure as INDEX_NONE. Same limitation as
	 * MonolithBlueprintInternal::ResolveEnumValueFromRaw, recorded for the same reason.
	 */
	inline bool ResolveEnumValueStrict(const UEnum* Enum, const FString& RawValue, int64& OutValue, FString& OutError)
	{
		if (!Enum)
		{
			OutError = TEXT("Property is enum-typed but carries no UEnum, so no value can be validated against it.");
			return false;
		}

		int64 Value = Enum->GetValueByNameString(RawValue, EGetByNameFlags::None);

		if (Value == INDEX_NONE)
		{
			const FString FirstName = Enum->GetNameStringByIndex(0);
			int32 UnderscoreIdx = INDEX_NONE;
			if (FirstName.FindChar(TEXT('_'), UnderscoreIdx))
			{
				Value = Enum->GetValueByNameString(FirstName.Left(UnderscoreIdx + 1) + RawValue, EGetByNameFlags::None);
			}
		}

		if (Value == INDEX_NONE)
		{
			// FCString::IsNumeric accepts "-", "+" and "." with no digits at all, and Atoi64
			// answers 0 for each — which IsStorableEnumValue would then happily accept as entry 0,
			// i.e. exactly the bug this function exists to stop. Require a digit first.
			bool bHasDigit = false;
			for (const TCHAR Char : RawValue)
			{
				if (FChar::IsDigit(Char)) { bHasDigit = true; break; }
			}
			if (bHasDigit && RawValue.IsNumeric())
			{
				const int64 AsInt = FCString::Atoi64(*RawValue);
				if (IsStorableEnumValue(Enum, AsInt))
				{
					Value = AsInt;
				}
			}
		}

		if (Value == INDEX_NONE)
		{
			OutError = FString::Printf(
				TEXT("Invalid value '%s' for enum '%s'. Valid values: %s. ")
				TEXT("Refused rather than coerced — an unrecognised name used to be stored as entry 0, ")
				TEXT("which silently reverted whatever was set before."),
				*RawValue, *Enum->GetName(), *DescribeValidValues(Enum));
			return false;
		}

		OutValue = Value;
		return true;
	}

	/**
	 * Resolve a JSON NUMBER to an enum value, or refuse. Non-integral numbers are refused
	 * outright rather than truncated, for the same reason names are not coerced.
	 */
	inline bool ResolveEnumValueStrictNumeric(const UEnum* Enum, double InNumber, int64& OutValue, FString& OutError)
	{
		if (!Enum)
		{
			OutError = TEXT("Property is enum-typed but carries no UEnum, so no value can be validated against it.");
			return false;
		}

		if (InNumber != FMath::TruncToDouble(InNumber))
		{
			OutError = FString::Printf(
				TEXT("Invalid value %f for enum '%s': enum values are integers. Valid values: %s."),
				InNumber, *Enum->GetName(), *DescribeValidValues(Enum));
			return false;
		}

		const int64 AsInt = static_cast<int64>(InNumber);
		if (!IsStorableEnumValue(Enum, AsInt))
		{
			OutError = FString::Printf(
				TEXT("Invalid value %lld for enum '%s': the enum declares no such value. Valid values: %s. ")
				TEXT("Refused rather than coerced."),
				AsInt, *Enum->GetName(), *DescribeValidValues(Enum));
			return false;
		}

		OutValue = AsInt;
		return true;
	}
}
